from ..common import CustomIntEnum


class ArkDexNpcCardStrategy(CustomIntEnum):
    RANDOM = "RANDOM", 0
    FIXED_ORDER = "FIXED_ORDER", 1
    PREFER_ELEMENT_0 = "PREFER_ELEMENT_0", 2
    PREFER_ELEMENT_1 = "PREFER_ELEMENT_1", 3
    PREFER_ELEMENT_2 = "PREFER_ELEMENT_2", 4
    PREFER_RANGED = "PREFER_RANGED", 5
    PREFER_RARITY = "PREFER_RARITY", 6
    COUNTER_PLAYER_MAJOR = "COUNTER_PLAYER_MAJOR", 7
    COUNTERED_BY_PLAYER_MAJOR = "COUNTERED_BY_PLAYER_MAJOR", 8
    BAG_MIN_ELEMENT = "BAG_MIN_ELEMENT", 9
    BAG_MAX_ELEMENT = "BAG_MAX_ELEMENT", 10
    RANDOM_FROM_ALL = "RANDOM_FROM_ALL", 11
