from ..common import CustomIntEnum


class ArkventTaskActorType(CustomIntEnum):
    NONE = "NONE", 0
    NPC = "NPC", 1
    FURNITURE = "FURNITURE", 2
    TRIGGER = "TRIGGER", 3
    COLLIDER = "COLLIDER", 4
    VIRTUAL = "VIRTUAL", 5
    NPC_SHOW_ONLY = "NPC_SHOW_ONLY", 6
    FURNITURE_SHOW_ONLY = "FURNITURE_SHOW_ONLY", 7
    TRIGGER_SHOW_ONLY = "TRIGGER_SHOW_ONLY", 8
    SCENE_OBJECT_CONTROL = "SCENE_OBJECT_CONTROL", 9
    EFFECT = "EFFECT", 10
    FLAG_EXPRESSION = "FLAG_EXPRESSION", 99
