from ..common import CustomIntEnum


class ItemReslockStatus(CustomIntEnum):
    NOT_SUPPORT_RESLOCK = "NOT_SUPPORT_RESLOCK", 0
    MAT_GACHA_RESLOCK_BLACKLIST = "MAT_GACHA_RESLOCK_BLACKLIST", 1
    CHAR_POTENTIAL_BLACKLIST = "CHAR_POTENTIAL_BLACKLIST", 2
    COMMON_BLACKLIST = "COMMON_BLACKLIST", 999
    CAN_RESLOCK = "CAN_RESLOCK", 1000
