from ..common import BaseStruct


class RL06EndingText(BaseStruct):
    summaryScrapGot: str
    summaryScrapSold: str
    summaryScrapLost: str
    summaryScrapMove: str
    summaryScrapBuff: str
    summaryScrapLegacy: str
    summaryMeetWeather: str
    summaryWeatherClear: str
    summaryBubbleBandit: str
    summaryBubbleTreasure: str
    summaryBubbleEvent: str
    summarySavageCamp: str
    summaryScrapShop: str
    summaryScrapShopBuy: str
    summaryScrapShopIdentify: str
    summaryDoor: str
    summaryTreeHole: str
    summaryEvacuate: str
    summaryEmployCamp: str
    summaryEmployRecruit: str
    summaryMercenaryLeave: str
    summaryEncounterBattleWin: str
    summaryEncounterBattleLose: str
    summaryExchangeScrap: str
    summaryExpeditionGoEnding: str
    summaryExpeditionBackEnding: str
    summaryActor: str
    summaryTop: str
    summaryZone: str
    summaryEnding: str
    summaryDifficultyZone: str
    summaryDifficultyEnding: str
    summaryMode: str
    summarySupport: str
    summaryGroup: str
    summaryNormalRecruit: str
    summaryDirectRecruit: str
    summaryFriendRecruit: str
    summaryFreeRecruit: str
    summaryMonthRecruit: str
    summaryUpgrade: str
    summaryCompleteEnding: str
    summaryEachZone: str
    summaryMeetSpZone: str
    summaryPerfectBattle: str
    summaryMeetBattle: str
    summaryMeetEvent: str
    summaryMeetShop: str
    summaryMeetTreasure: str
    summaryMeetSecretpath: str
    summaryExchangeRelic: str
    summaryMeetTrade: str
    summaryBuy: str
    summaryBuyWithPriceId: str
    summaryInvest: str
    summaryGet: str
    summaryRelic: str
    summarySafeHouse: str
    summaryFailEnd: str
    summaryStockRecruitTicket: str
    summaryDuelWin: str
    summaryDuelTie: str
    summaryDuelLose: str
    summaryExpeditionGo: str
    summaryExpeditionBack: str
