from enum import StrEnum


class RoguelikeRewardExDropTagSrcType(StrEnum):
    NONE = "NONE"
    TREASURE = "TREASURE"
    TOTEM = "TOTEM"
    EXPLORE_TOOL = "EXPLORE_TOOL"
    COPPER = "COPPER"
    EVIL_TEMPLE = "EVIL_TEMPLE"
    TREASURE_MAP = "TREASURE_MAP"
    LOOP_CHIP = "LOOP_CHIP"
    STEP = "STEP"
    GREED = "GREED"
    GOLDEN_AGE = "GOLDEN_AGE"
    ADVENTURER_EXTRA = "ADVENTURER_EXTRA"
