from ..common import CustomIntEnum


class SandboxPermItemType(CustomIntEnum):
    NONE = "NONE", 0
    TACTICAL = "TACTICAL", 1
    BUILDING = "BUILDING", 2
    BUILDINGMAT = "BUILDINGMAT", 3
    FOOD = "FOOD", 4
    FOODMAT = "FOODMAT", 5
    SPECIALMAT = "SPECIALMAT", 6
    COIN = "COIN", 9
    CRAFT = "CRAFT", 10
    PLACEHOLDER = "PLACEHOLDER", 11
    STAMINAPOT = "STAMINAPOT", 12
    ANIMAL = "ANIMAL", 13
    INSECT = "INSECT", 14
    SLUGITEM = "SLUGITEM", 15
    RELIC = "RELIC", 16
    RECIPE = "RECIPE", 17
    PRODUCT = "PRODUCT", 18
    TOOLKIT = "TOOLKIT", 19
    RANDRELIC = "RANDRELIC", 20
    RANDRECIPE = "RANDRECIPE", 21
    CURRENCY = "CURRENCY", 22
    COOKBOOK = "COOKBOOK", 23
    BASEBUILDING = "BASEBUILDING", 24
    BASECOIN = "BASECOIN", 25
    BASEANIMAL = "BASEANIMAL", 26
    BASETACTICAL = "BASETACTICAL", 27
    TECHPOINT = "TECHPOINT", 28
